# -*- coding: utf-8 -*-
"""breadh_first_search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19BquwK24aZNKrtFeNShYR7HbAGS68q1D
"""

# Note: objective() is a method that verifies if visiting_node is the desired 
# node.

def breadth_first_search(node):
  search_queue = deque()
  search_queue += graph[node]
  searched_nodes = []
  while search_queue:
    visiting_node = search_queue.popleft()
    if not visiting_node in searched_nodes:
      if objective(visiting_node):
        print(visiting_node)
        return True
      else:
        search_queue += graph[visiting_node]
        searched_nodes.append(visiting_node)
  return False