# -*- coding: utf-8 -*-
"""quicksort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOqNFfdAPNdk-v09TQ0Hdnz95_6gn9qu
"""

def quicksort(array):
  if len(array) < 2:
    return array
  else:
    pivot = array[0]
    left = [i for i in array[1:] if i <= pivot]
    right = [i for i in array[1:] if i > pivot]
    return quicksort(left) + [pivot] + quicksort(right)